#include "DungeonOrchestrator.h"
#include "BspMathTree.h" // Enlace directo a tu clase vacía y pura de C++
#include "Containers/Queue.h"

ADungeonOrchestrator::ADungeonOrchestrator()
{
    // Desactivamos el Tick para ahorrar recursos, ya que la generación ocurre por eventos
        PrimaryActorTick.bCanEverTick = false;

            // Inicializamos el componente para Suelos y Techos como la raíz del Actor
                FloorCeilingISM = CreateDefaultSubobject<UInstancedStaticMeshComponent>(TEXT("FloorCeilingISMComponent"));
                    RootComponent = FloorCeilingISM;

                        // Inicializamos el componente para las Paredes y lo adjuntamos a la raíz
                            WallsISM = CreateDefaultSubobject<UInstancedStaticMeshComponent>(TEXT("WallsISMComponent"));
                                WallsISM->SetupAttachment(RootComponent);
                                }

                                void ADungeonOrchestrator::BeginPlay()
                                {
                                    Super::BeginPlay();
                                        
                                            // 1. Cargar las mallas asignadas en el Blueprint
                                                CargarRecursosAsincronos();

                                                    // 2. Disparar la generación de un sector (Chunk) de prueba
                                                        // Parámetros: StartX=0, StartY=0, Width=200, Height=200, Seed=54321
                                                            BuildAndRenderChunk(0, 0, 200, 200, 54321);
                                                            }

                                                            void ADungeonOrchestrator::CargarRecursosAsincronos()
                                                            {
                                                                // Carga síncrona segura de los Soft Object Pointers expuestos al editor
                                                                    if (AssetSueloTecho.IsValid())
                                                                        {
                                                                                FloorCeilingISM->SetStaticMesh(AssetSueloTecho.LoadSynchronous());
                                                                                    }
                                                                                        if (AssetPared.IsValid())
                                                                                            {
                                                                                                    WallsISM->SetStaticMesh(AssetPared.LoadSynchronous());
                                                                                                        }
                                                                                                        }

                                                                                                        void ADungeonOrchestrator::BuildAndRenderChunk(int32 StartX, int32 StartY, int32 Width, int32 Height, int32 Seed)
                                                                                                        {
                                                                                                            FRandomStream ChunkStream(Seed);

                                                                                                                // =========================================================================
                                                                                                                    // CAPA 1: DATOS (Instanciación y procesamiento en tu clase pura de C++)
                                                                                                                        // =========================================================================
                                                                                                                            TSharedPtr<FBspMathTree> RootNode = TMakeShared<FBspMathTree>(StartX, StartY, Width, Height);

                                                                                                                                TQueue<TSharedPtr<FBspMathTree>> Queue;
                                                                                                                                    Queue.Enqueue(RootNode);
                                                                                                                                        TSharedPtr<FBspMathTree> Current;

                                                                                                                                            while (Queue.Dequeue(Current))
                                                                                                                                                {
                                                                                                                                                        // Se ejecuta tu lógica de pivote dinámico sin tocar librerías pesadas de UE5
                                                                                                                                                                if (Current->SplitWithDynamicPivot(20, 60, ChunkStream))
                                                                                                                                                                        {
                                                                                                                                                                                    Queue.Enqueue(Current->LeftChild);
                                                                                                                                                                                                Queue.Enqueue(Current->RightChild);
                                                                                                                                                                                                        }
                                                                                                                                                                                                            }

                                                                                                                                                                                                                // Extraemos las hojas finales usando la función auxiliar recursiva de tipo puro
                                                                                                                                                                                                                    TArray<TSharedPtr<FBspMathTree>> Leaves;
                                                                                                                                                                                                                        GetLeavesRecursively(RootNode, Leaves);

                                                                                                                                                                                                                            // =========================================================================
                                                                                                                                                                                                                                // CAPA 2: LÓGICA Y FLAGS (El C++ puro genera el DTO de datos planos)
                                                                                                                                                                                                                                    // =========================================================================
                                                                                                                                                                                                                                        TArray<FChunkRoomData> CompiledSectorData;
                                                                                                                                                                                                                                            const float ConfiguredWallThickness = 20.0f; // Grosor de los muros en centímetros

                                                                                                                                                                                                                                                for (const auto& LeafNode : Leaves)
                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                            if (LeafNode.IsValid())
                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                // El nodo invoca internamente a GetRoomGeometry y empaqueta todo en FChunkRoomData
                                                                                                                                                                                                                                                                                            FChunkRoomData RoomData = LeafNode->ProcessRoomLogicAndFlags(ConfiguredWallThickness, ChunkStream);
                                                                                                                                                                                                                                                                                                        CompiledSectorData.Add(RoomData);
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                        // =========================================================================
                                                                                                                                                                                                                                                                                                                            // CAPA 3: VISUALIZACIÓN (El orquestador dibuja los paquetes puros en Unreal)
                                                                                                                                                                                                                                                                                                                                // =========================================================================
                                                                                                                                                                                                                                                                                                                                    for (const FChunkRoomData& Room : CompiledSectorData)
                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                RenderRoomByFaces(Room);
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                        // En este punto, 'RootNode' y todo el árbol matemático de C++ se eliminan de la memoria 
                                                                                                                                                                                                                                                                                                                                                            // de forma automática al salir de ámbito, dejando el juego limpio de estructuras basura.
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                            void ADungeonOrchestrator::RenderRoomByFaces(const FChunkRoomData& RoomData)
                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                // Dimensión base de tus mallas modulares en el motor (Fbx estándar de 100x100x100 cm)
                                                                                                                                                                                                                                                                                                                                                                    const float UnrealMeshBaseSize = 100.0f; 

                                                                                                                                                                                                                                                                                                                                                                        // 1. Renderizar instancias de Suelo y Techo
                                                                                                                                                                                                                                                                                                                                                                            FTransform FloorT(RoomData.FloorFace.Rotation, RoomData.FloorFace.Location, RoomData.FloorFace.Scale / UnrealMeshBaseSize);
                                                                                                                                                                                                                                                                                                                                                                                FloorCeilingISM->AddInstance(FloorT);

                                                                                                                                                                                                                                                                                                                                                                                    FTransform CeilingT(RoomData.CeilingFace.Rotation, RoomData.CeilingFace.Location, RoomData.CeilingFace.Scale / UnrealMeshBaseSize);
                                                                                                                                                                                                                                                                                                                                                                                        FloorCeilingISM->AddInstance(CeilingT);

                                                                                                                                                                                                                                                                                                                                                                                            // 2. Renderizar mallas independientes por cada una de las 4 caras laterales (Muros)
                                                                                                                                                                                                                                                                                                                                                                                                FTransform WallNT(RoomData.WallNorth.Rotation, RoomData.WallNorth.Location, RoomData.WallNorth.Scale / UnrealMeshBaseSize);
                                                                                                                                                                                                                                                                                                                                                                                                    WallsISM->AddInstance(WallNT);

                                                                                                                                                                                                                                                                                                                                                                                                        FTransform WallST(RoomData.WallSouth.Rotation, RoomData.WallSouth.Location, RoomData.WallSouth.Scale / UnrealMeshBaseSize);
                                                                                                                                                                                                                                                                                                                                                                                                            WallsISM->AddInstance(WallST);

                                                                                                                                                                                                                                                                                                                                                                                                                FTransform WallET(RoomData.WallEast.Rotation, RoomData.WallEast.Location, RoomData.WallEast.Scale / UnrealMeshBaseSize);
                                                                                                                                                                                                                                                                                                                                                                                                                    WallsISM->AddInstance(WallET);

                                                                                                                                                                                                                                                                                                                                                                                                                        FTransform WallWT(RoomData.WallWest.Rotation, RoomData.WallWest.Location, RoomData.WallWest.Scale / UnrealMeshBaseSize);
                                                                                                                                                                                                                                                                                                                                                                                                                            WallsISM->AddInstance(WallWT);

                                                                                                                                                                                                                                                                                                                                                                                                                                // 3. Renderizar Elementos Interactivos o Dinámicos (Spawners de Blueprints reales)
                                                                                                                                                                                                                                                                                                                                                                                                                                    FActorSpawnParameters SpawnParams;
                                                                                                                                                                                                                                                                                                                                                                                                                                        for (const FDecorFlagData& Decor : RoomData.ApprovedDecorations)
                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (Decor.Type == EDecorationType::CeilingLight && BlueprintLuzTecho)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Las mallas con luces físicas o lógica de Blueprint sí requieren un Spawn individual
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    GetWorld()->SpawnActor<AActor>(BlueprintLuzTecho, Decor.Location, Decor.Rotation, SpawnParams);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                void ADungeonOrchestrator::GetLeavesRecursively(TSharedPtr<FBspMathTree> CurrentNode, TArray<TSharedPtr<FBspMathTree>>& OutLeaves)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!CurrentNode.IsValid()) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (CurrentNode->IsLeaf())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    OutLeaves.Add(CurrentNode);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Descenso ordenado por las ramas de tu clase pura
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        GetLeavesRecursively(CurrentNode->LeftChild, OutLeaves);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            GetLeavesRecursively(CurrentNode->RightChild, OutLeaves);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }